### ISSUE TITLE
The new drive don’t support Traverse and ALTER commands

### ISSUE THREAD

**Issue by holocentric-bmsnext** [orientechnologies/OrientDB.Net#21]
Queries like "ALTER CLASS ...", "ALTER PROPERTY ", "TRAVERSE bothE(),bothV()....", "TRAVERSE inE(),outV()...." 
don't work when executed from the code using the new driver. These queries execute successfully in the Studio. 
The traverse query also have the same issue as the existing driver. see https://github.com/orientechnologies/OrientDB-NET.binary/issues/149

**Comment by riker09** [comment]
I think I'm having the same issue. When I try to execute this statement:

```sql
ALTER CLASS `MyClassName` STRICTMODE true
```

the driver throws:

```
InnerException	{System.NullReferenceException: Object reference not set to an instance of an object.
   at OrientDB.Net.ConnectionProtocols.Binary.Operations.DocumentResultDatabaseCommandOperation.CreateRequest(Int32 sessionId, Byte[] token) in C:\Projekte\OrientDB.Net\src\OrientDB.Net.ConnectionProtocols.Binary\Operations\DocumentResultDatabaseCommandOperation.cs:line 44
   at OrientDB.Net.ConnectionProtocols.Binary.Core.OrientDBBinaryConnectionStream.Process[T](IOrientDBOperation`1 operation, OrientDBNetworkConnection stream) in C:\Projekte\OrientDB.Net\src\OrientDB.Net.ConnectionProtocols.Binary\Core\OrientDBBinaryConnectionStream.cs:line 203
   at OrientDB.Net.ConnectionProtocols.Binary.Core.OrientDBBinaryConnectionStream.Send[T](IOrientDBOperation`1 operation) in C:\Projekte\OrientDB.Net\src\OrientDB.Net.ConnectionProtocols.Binary\Core\OrientDBBinaryConnectionStream.cs:line 170
   at OrientDB.Net.ConnectionProtocols.Binary.Core.OrientDBCommand.Execute(String query) in C:\Projekte\OrientDB.Net\src\OrientDB.Net.ConnectionProtocols.Binary\Core\OrientDBBinaryQuery.cs:line 36
   at OrientDB.Net.ConnectionProtocols.Binary.Core.OrientDBBinaryConnection.ExecuteCommand(String sql) in C:\Projekte\OrientDB.Net\src\OrientDB.Net.ConnectionProtocols.Binary\Core\OrientDBBinaryConnection.cs:line 77
[...]
```
